// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9TINbqAKGXJuJvPHFS1OzBel5ome4Kwc',
    appId: '1:602192321200:web:3f336e9494f33c6a337975',
    messagingSenderId: '602192321200',
    projectId: 'authfirebase-3a86d',
    authDomain: 'authfirebase-3a86d.firebaseapp.com',
    storageBucket: 'authfirebase-3a86d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLvw2H3qZsXt0p-2AjLBJwjfuw7f5zCW0',
    appId: '1:602192321200:android:d27bc5b32a073836337975',
    messagingSenderId: '602192321200',
    projectId: 'authfirebase-3a86d',
    storageBucket: 'authfirebase-3a86d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOGGLr2GxDgSILiq5JDaX2nv6IyTaC3-c',
    appId: '1:602192321200:ios:b69cbddb5ad90f6d337975',
    messagingSenderId: '602192321200',
    projectId: 'authfirebase-3a86d',
    storageBucket: 'authfirebase-3a86d.appspot.com',
    iosBundleId: 'com.example.uipages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOGGLr2GxDgSILiq5JDaX2nv6IyTaC3-c',
    appId: '1:602192321200:ios:d682603adec7ea2b337975',
    messagingSenderId: '602192321200',
    projectId: 'authfirebase-3a86d',
    storageBucket: 'authfirebase-3a86d.appspot.com',
    iosBundleId: 'com.example.uipages.RunnerTests',
  );
}
